title: Alessandro Cifani
description: Personal website and blog

author: Alessandro Cifani
email: alessandro.cifani@gmail.com

baseurl: /
permalink: /:year/:month/:title
paginate: 10
markdown: kramdown

gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - scripts/
